services:
  db:
    build:
      context: ./docker
      dockerfile: dockerfile.db
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  app:
    build:
      context: .
      dockerfile: ./docker/dockerfile.app
    container_name: hono-app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./app"
        target: "/workspace/app"
      - node_modules:/workspace/app/node_modules
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
  node_modules:
